### ISSUE TITLE
Events aren't fired when dispatching event using chrome dev console

### ISSUE THREAD

**Issue by weibeu** [orstavik/ClickIsTrusted#7]
How to reproduce:
- Enable the extension.
- Open up any random webpage.
- Attach the event listener using developer console. For example: `window.addEventListener("mousedown", e=>console.log(e.type, e.x, e.y, e));`
- Fire the event using developer console. For example: `window.dispatchEvent(new MouseEvent("mousedown-is-trusted", {composed: true, bubbles: true, clientX: 12, clientY: 34, button: 0, buttons: 1}));`

Expected: Log in console of mousedown event and isTrusted set to true.
Actual: No output in console; event is not dispatched or handled by extension.

**Comment by weibeu** [comment]
For reference: 
![image](https://user-images.githubusercontent.com/34530901/106280831-6e32b280-6264-11eb-9f1e-e18821cfb691.png)

**Comment by orstavik** [comment]
I think your issue is: 
1. you need to "pin" the extension in chrome. click on the extension symbol in the top right corner. and then click on the pin sign next to ClickIsTrusted. When you do this, a little icon of a mouse cursor arrow will appear in the top right corner of the browser.
2. go to the tab with where you want to use ClickIsTrusted. And here click on the ClickIsTrusted extension icon (mouse cursor). This will activate the extension. it will now turn red.

alert! the extension is tab specific, it will be active only in selected tabs.

3. now, add the event listener again, and then try to dispatch the test "mousedown-is-trusted" event.

**Comment by weibeu** [comment]
Oh, I had forgot to mention that I did tried that way too as it was mentioned in README as well but couldn't get working. I am not sure on what I am doing wrong. But I tried as you said but couldn't get it working.
![image](https://user-images.githubusercontent.com/34530901/106318398-e796c900-6295-11eb-87fd-32877a0ff9c7.png)

**Comment by weibeu** [comment]
Also, tried after ClickIsTrusted was loaded.
![image](https://user-images.githubusercontent.com/34530901/106318716-5411c800-6296-11eb-9810-1158c0b1368b.png)

**Comment by orstavik** [comment]
Hm.. I get a big status bar with a big "cancel" button under the navigation bar when i activate the plugin in Chrome (on Ubuntu Linux).

Which Chrome and OS are you using?

**Comment by weibeu** [comment]
Yes yes, I got that too saying this extension is debugging chrome. It's just hidden I suppose. I am using latest chrome and windows 10 latest.

**Comment by orstavik** [comment]
Ok. Just tested ClickIsTrusted on Chrome 87.0.4280.141 (Official Build) (64-bit) on windows 10. And it did work, so no update in Chrome or Windows have broken it.

I am guessing the following might trip you up:
1. reloading the page. After you have activated and made the cursor red. Try to turn on and off the little red mouse cursor. Dont really know why that happens..
2. activating ClickIsTrusted in a different tab. ClickIsTrusted is tab specific. It should in theory only allow clicks in tabs that you have pressed the icon in. That makes it a little safer.
3. I would try to reinstall the plugin. Then make sure you dont remove the cancel bar. And that you activate (or turn it off/on again) inside the tab that you are trying to run trusted events in.

other things that might go wrong is antivirus, other extensions... ?

**Comment by orstavik** [comment]
There is a clear argument to be made for having less security and just enable ClickIsTrusted for all tabs.. The limitations is hard to make right, and current restrictions make the extension too fragile. I should probably enable the extension for all tabs, and instead make some other kind of security measures: Small popup notice that needs to be closed manually after each session. uglier warning icon when click is trusted is active. something like that..

But. I dont manage to do that in a jiffy, so it must wait a little bit. )

**Comment by weibeu** [comment]
Really thanks for helping me with it. Just mentioning that I was trying this on Chrome 88
![image](https://user-images.githubusercontent.com/34530901/106353991-8f52dc00-6314-11eb-96f5-ced5fd26a53e.png)

**Comment by weibeu** [comment]
Its really strange but somehow I too got it working. So it doesn't works normally but as you said, when I click over the extension few of times and toggle it on and off along with few combinations of page reloads and repeating the same, it does works. I can't really figure out why this is happening though.

**Comment by weibeu** [comment]
So I noticed this behavior when I got extension working and after page makes any requests or does any network activity, the extensions does receives the native events and console logs it normally but doesn't dispatches it. As in first screenshot.
![image](https://user-images.githubusercontent.com/34530901/106355521-82d38100-631e-11eb-8628-d6f6a28067fc.png)

When this happens and I restart the extension by clicking it icon changing it from red ---> black ---> red and manually dispatch the event again then it works fine as expected like in this screenshot.
![image](https://user-images.githubusercontent.com/34530901/106355556-cb8b3a00-631e-11eb-8f23-57a9a7eefd4a.png)

**Comment by weibeu** [comment]
Moreover, it doesn't works at all on some specific sites. The above tests were those I tried on google.com.

**Comment by weibeu** [comment]
Found it why this wasn't working. From [Chrome Debugger API docs](https://developer.chrome.com/docs/extensions/reference/debugger/#notes):
> As of today, attaching to the tab by means of the debugger API and using embedded Chrome DevTools with that tab are mutually exclusive. **If user invokes Chrome DevTools while extension is attached to the tab, debugging session is terminated.** Extension can re-establish it later.

This is what happening all of time. I was trying to invoke the events from the chrome debugger console which in turn keeps terminating the chrome.debugger session. And reloading/restarting the extension re-establishes the chrome.debugger session.

**Comment by orstavik** [comment]
Great catch! This essentially means that:
1. when you turn on devtools,
2. then you turn off ClickIsTrusted.
(but the ClickIsTrusted icon doesn't catch this bug, and so it stays red when it should turn itself off).

The (temporary) solution would be to always stop and then restart again ClickIsTrusted when you open devtools. Please correct me if I summarized this incorrectly:)

Note for future fix: 
Don't like the current design with tab id isolation. So, I think that for version 2, ClickIsTrusted should (if possible):
1. work for all tabs
2. have a red, attention-grabbing, ugly warning label up near the activation button. So that the user always wishes to turn the plugin off when it is not being actively used.

Thank you very much weibeu for your very interesting and very useful issue/contribution:)
Ivar
